### ISSUE TITLE
Specdm compatibility 

### ISSUE THREAD

**Issue by mexikoedi** [AaronMcKenney/ttt2-role_beac#2]
If the beacon dies and spawns in the specdm the hud of the beacon is still active and interferes with the normal hud.
The buffs are also present in specdm.
Could you look into it maybe? 

Maybe this code can help: https://github.com/mexikoedi/ttt2_role_med/blob/5b5e4948263951bc611f2df378ba778a24cf1f79/ttt2_role_med/lua/terrortown/entities/roles/medic/shared.lua#L94

**Comment by AaronMcKenney** [comment]
I'm not all that familiar with SpecDM. Does SpecDM remove TTT2 roles when they are resurrected like this? I don't think the Beacon HUD would appear unless they were still a Beacon, but I could be mistaken...

**Comment by mexikoedi** [comment]
The specdm does not remove the roles from the player. 
They are still beacon or whatever role they were in spectator mode and in specdm too. (To prevent issues if they respawn. (i think))
That's why the hud is still there. 
The code from above is an example for the medic role where popups and role changes are used. 

The code prevents these stuff in specdm and can be used for other roles as well (needs to be modified a bit) if they use stuff which could interfere in specdm. (Like maybe the banker role too?)

**Comment by AaronMcKenney** [comment]
I'd be surprised if the Banker would interfere with SpecDM (it reuses some Amnesiac logic for popups, and that role doesn't seem to have any special handling for SpecDM), but if you find an issue with that role, you can file another bug.

I'll look into fixing this SpecDM issue for Beacon.

**Comment by mexikoedi** [comment]
Okay, thanks for looking into it. 
The amnesiac only does a popup if he confirms bodies if i remember the role correctly. In specdm you can't confirm bodies so the popup is not triggered.
I will test the banker role later and will create an issue if there is something.

**Comment by mexikoedi** [comment]
Small update to this issue. 
I noticed that the buffs are also present in specdm. 
I updated the original issue descritpion.

**Comment by AaronMcKenney** [comment]
HUD and buff discrepancies should be fixed in latest commit (sans speed change, at least on my end. Hope that's ok):
https://github.com/AaronMcKenney/ttt2-role_beac/commit/32d0b229d9300e89c9f93104c685bab78a88d1e5

**Comment by AaronMcKenney** [comment]
Just realized that I should have let you close this issue. Sorry! Feel free to reopen if you see some additional problem with it.

**Comment by mexikoedi** [comment]
It's alright, seems good.
If you tested it and everything worked as it should then it's fine. 
Thank you.
